name: enc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
